service: default

runtime: java11
#env: flex

#runtime_config:
  #jdk: openjdk8
  
handlers:
- url: /.*
  script: this field is required, but ignored  
manual_scaling:
    instances: 1
    
#inbound_services:
  # - warmup